Extension { #name : #Float }

{ #category : #'*RenoirSt-UnitsCompatibility' }
Float >> cm [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	^super cm
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Float >> in [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	^super in
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Float >> mm [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	^super mm
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Float >> pc [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	^super pc
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Float >> rad [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	^super rad
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Float >> s [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	^super s
]
