Extension { #name : #Integer }

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> Hz [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super Hz
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> cm [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super cm
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> in [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super in
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> kHz [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super kHz
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> mm [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super mm
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> pc [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super pc
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> pt [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super pt
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> px [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super px
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> rad [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super rad
]

{ #category : #'*RenoirSt-UnitsCompatibility' }
Integer >> s [
	"This method overrides the one in RenoirSt to be compatible with the Units package"
	 ^super s
]
