"
A CssNoAlphaChannelProvided represents the absence of an alpha channel. So this color is considered opaque.

"
Class {
	#name : #CssNoAlphaChannelProvided,
	#superclass : #CssAlphaChannel,
	#category : #'RenoirSt-Core-Colors'
}

{ #category : #Enumerating }
CssNoAlphaChannelProvided >> componentsDo: aBlockClosure separatedBy: aSeparationBlock [ 
	
]

{ #category : #Accessing }
CssNoAlphaChannelProvided >> functionNameFor: aString [ 
	
	^aString 
]
