Tests
testBorderProperties

	self
		assert: CssConstants fill equals: 'fill';
		assert: CssConstants stretch equals: 'stretch';
		assert: CssConstants collapse equals: 'collapse';
		assert: CssConstants dashed equals: 'dashed';
		assert: CssConstants dotted equals: 'dotted';
		assert: CssConstants double equals: 'double';
		assert: CssConstants groove equals: 'groove';
		assert: CssConstants inset equals: 'inset';
		assert: CssConstants medium equals: 'medium';
		assert: CssConstants outset equals: 'outset';
		assert: CssConstants ridge equals: 'ridge';
		assert: CssConstants separate equals: 'separate';
		assert: CssConstants solid equals: 'solid';
		assert: CssConstants thick equals: 'thick';
		assert: CssConstants thin equals: 'thin'