"
A CssConstants is shared place providing easy access to property constants values

"
Class {
	#name : #CssConstants,
	#superclass : #Object,
	#category : 'RenoirSt-Common'
}

{ #category : #'Accessing - Positioning' }
CssConstants class >> absolute [

	^'absolute'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> always [  

	^'always'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> armenian [  

	^'armenian'
]

{ #category : #Accessing }
CssConstants class >> auto [ 

	^'auto'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> avoid [  

	^'avoid'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> baseline [  

	^'baseline'
]

{ #category : #'Accessing - Text' }
CssConstants class >> blink [

	^'blink'
]

{ #category : #'Accessing - Display' }
CssConstants class >> block [
	"This value causes an element to generate a block box."

	^ 'block'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> bold [ 

	^'bold'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> bolder [ 

	^'bolder'
]

{ #category : #'Accessing - Background' }
CssConstants class >> borderBox [
	
	^'border-box'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> both [ 

	^'both'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> bottom [ 

	^'bottom'
]

{ #category : #'Accessing - Text' }
CssConstants class >> breakWord [
	^'break-word'
]

{ #category : #'Accessing - Text' }
CssConstants class >> capitalize [

	^'capitalize'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> caption [ 

	^'caption'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> center [

	^'center'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> circle [ 

	^'circle'
]

{ #category : #'Accessing - Background' }
CssConstants class >> closestCorner [
	
	^'closest-corner'
]

{ #category : #'Accessing - Background' }
CssConstants class >> closestSide [
	
	^'closest-side'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> collapse [ 

	^'collapse'
]

{ #category : #'Accessing - Size' }
CssConstants class >> contain [

	^'contain'
]

{ #category : #'Accessing - Background' }
CssConstants class >> contentBox [
	
	^'content-box'
]

{ #category : #'Accessing - Size' }
CssConstants class >> cover [

	^'cover'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> crosshair [ 

	^'crosshair'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> dashed [

	^'dashed'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> decimal [  

	^'decimal'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> decimalLeadingZero [

	^'decimal-leading-zero'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> default [  

	^'default'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> disc [ 

	^'disc'
]

{ #category : #'Accessing - Text' }
CssConstants class >> dot [

	^'dot'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> dotted [

	^'dotted'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> double [

	^'double'
]

{ #category : #'Accessing - Text' }
CssConstants class >> doubleCircle [
	
	^'double-circle'
]

{ #category : #'Accessing - Text' }
CssConstants class >> ellipsis [

	^'ellipsis'
]

{ #category : #Accessing }
CssConstants class >> even [

	^'even'
]

{ #category : #'Accessing - Background' }
CssConstants class >> farthestCorner [
	
	^'farthest-corner'
]

{ #category : #'Accessing - Background' }
CssConstants class >> farthestSide [
	
	^'farthest-side'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> fill [
	
	^'fill'
]

{ #category : #'Accessing - Text' }
CssConstants class >> filled [
	
	^'filled'
]

{ #category : #'Accessing - Attachments' }
CssConstants class >> fixed [
	^ 'fixed'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> georgian [   

	^'georgian'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> groove [

	^'groove'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> help [ 

	^'help'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> hidden [ 

	^'hidden'
]

{ #category : #Accessing }
CssConstants class >> hide [  

	^'hide'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> icon [ 

	^'icon'
]

{ #category : #Accessing }
CssConstants class >> inherit [ 

	^'inherit'
]

{ #category : #Accessing }
CssConstants class >> initial [

	^'initial'
]

{ #category : #'Accessing - Display' }
CssConstants class >> inline [
	"This value causes an element to generate one or more inline boxes."

	^ 'inline'
]

{ #category : #'Accessing - Display' }
CssConstants class >> inlineBlock [
	"This value causes an element to generate an inline-level block container. The inside of an inline-block is formatted as a block box, and the element itself is formatted as an atomic inline-level box."

	^ 'inline-block'
]

{ #category : #'Accessing - Display' }
CssConstants class >> inlineTable [
	
	^ 'inline-table'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> inset [

	^'inset'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> inside [ 

	^'inside'
]

{ #category : #Accessing }
CssConstants class >> invert [ 

	^'invert'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> italic [ 

	^'italic'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> justify [ 

	^'justify'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> left [ 

	^'left'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> lighter [ 

	^'lighter'
]

{ #category : #'Accessing - Text' }
CssConstants class >> lineThrough [

	^'line-through'
]

{ #category : #'Accessing - Display' }
CssConstants class >> listItem [
	"This value causes an element to generate a principal block box and a marker box."

	^ 'list-item'
]

{ #category : #'Accessing - Background' }
CssConstants class >> local [
	^ 'local'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> lowerAlpha [ 

	^'lower-alpha'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> lowerGreek [ 

	^'lower-greek'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> lowerLatin [

	^'lower-latin'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> lowerRoman [

	^'lower-roman'
]

{ #category : #'Accessing - Text' }
CssConstants class >> lowercase [

	^'lowercase'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> medium [

	^'medium'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> menu [ 

	^'menu'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> messageBox [

	^'message-box'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> middle [

	^'middle'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> move [    

	^'move'
]

{ #category : #'Accessing - Repeat' }
CssConstants class >> noRepeat [

	^'no-repeat'
]

{ #category : #Accessing }
CssConstants class >> none [ 

	^'none'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> normal [ 

	^'normal'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> notAllowed [

	^'not-allowed'
]

{ #category : #'Accessing - Text' }
CssConstants class >> nowrap [

	^'nowrap'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> oblique [  

	^'oblique'
]

{ #category : #Accessing }
CssConstants class >> odd [

	^'odd'
]

{ #category : #'Accessing - Text' }
CssConstants class >> open [

	^'open'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> outset [

	^'outset'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> outside [

	^'outside'
]

{ #category : #'Accessing - Text' }
CssConstants class >> over [
	
	^'over'
]

{ #category : #'Accessing - Text' }
CssConstants class >> overline [

	^'overline'
]

{ #category : #'Accessing - Background' }
CssConstants class >> paddingBox [
	
	^'padding-box'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> pointer [   

	^'pointer'
]

{ #category : #'Accessing - Text' }
CssConstants class >> pre [

	^'pre'
]

{ #category : #'Accessing - Text' }
CssConstants class >> preLine [ 

	^'pre-line '
]

{ #category : #'Accessing - Text' }
CssConstants class >> preWrap [

	^'pre-wrap'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> progress [ 

	^'progress'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> relative [

	^'relative'
]

{ #category : #'Accessing - Repeat' }
CssConstants class >> repeat [

	^'repeat'
]

{ #category : #'Accessing - Repeat' }
CssConstants class >> repeatX [

	^'repeat-x'
]

{ #category : #'Accessing - Repeat' }
CssConstants class >> repeatY [

	^'repeat-y'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> ridge [

	^'ridge'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> right [

	^'right'
]

{ #category : #'Accessing - Background' }
CssConstants class >> round [

	^'round'
]

{ #category : #'Accessing - Attachments' }
CssConstants class >> scroll [
	^ 'scroll'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> separate [  

	^'separate'
]

{ #category : #'Accessing - Text' }
CssConstants class >> sesame [
	
	^'sesame'
]

{ #category : #Accessing }
CssConstants class >> show [ 

	^'show'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> smallCaps [

	^'small-caps'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> smallCaption [
	^'small-caption'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> solid [

	^'solid'
]

{ #category : #'Accessing - Background' }
CssConstants class >> space [

	^'space'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> square [ 

	^'square'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> static [   

	^'static'
]

{ #category : #'Accessing - Fonts' }
CssConstants class >> statusBar [

	^'status-bar'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> stretch [

	 ^'stretch'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> sub [  

	^'sub'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> super [

	^'super'
]

{ #category : #'Accessing - Display' }
CssConstants class >> table [
	
	^ 'table'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableCaption [
	
	^ 'table-caption'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableCell [
	
	^ 'table-cell'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableColumn [
	
	^ 'table-column'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableColumnGroup [
	
	^ 'table-column-group'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableFooterGroup [
	
	^ 'table-footer-group'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableHeaderGroup [
	
	^ 'table-header-group'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableRow [
	
	^ 'table-row'
]

{ #category : #'Accessing - Display' }
CssConstants class >> tableRowGroup [
	
	^ 'table-row-group'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> text [ 

	^'text'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> textBottom [ 

	^'text-bottom'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> textTop [

	^'text-top'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> thick [

	^'thick'
]

{ #category : #'Accessing - Borders' }
CssConstants class >> thin [

	^'thin'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> top [ 

	^'top'
]

{ #category : #'Accessing - Text' }
CssConstants class >> triangle [
	
	^'triangle'
]

{ #category : #'Accessing - Text' }
CssConstants class >> under [
	
	^'under'
]

{ #category : #'Accessing - Text' }
CssConstants class >> underline [

	^'underline'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> upperAlpha [ 

	^'upper-alpha'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> upperLatin [ 

	^'upper-latin'
]

{ #category : #'Accessing - Lists' }
CssConstants class >> upperRoman [

	^'upper-roman'
]

{ #category : #'Accessing - Text' }
CssConstants class >> uppercase [

	^'uppercase'
]

{ #category : #Accessing }
CssConstants class >> vertical [

	^'vertical'
]

{ #category : #'Accessing - Positioning' }
CssConstants class >> visible [

	^'visible'
]

{ #category : #'Accessing - Cursors' }
CssConstants class >> wait [

	^'wait'
]
