"
A CssFontConstants is a shared pool providing access to common constants for fonts

"
Class {
	#name : #CssFontConstants,
	#superclass : #Object,
	#category : #'RenoirSt-Fonts'
}

{ #category : #'Font Variant' }
CssFontConstants class >> allPetiteCaps [
	
	^'all-petite-caps'
]

{ #category : #'Font Variant' }
CssFontConstants class >> allSmallCaps [
	
	^'all-small-caps'
]

{ #category : #'Font Variant' }
CssFontConstants class >> commonLigatures [
	
	^'common-ligatures'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> condensed [

		^ 'condensed'
]

{ #category : #'Font Variant' }
CssFontConstants class >> contextual [
	
	^'contextual'
]

{ #category : #'Generic Font Family' }
CssFontConstants class >> cursive [
	^ 'cursive'
]

{ #category : #'Font Variant' }
CssFontConstants class >> diagonalFractions [

	^'diagonal-fractions'
]

{ #category : #'Font Variant' }
CssFontConstants class >> discretionaryLigatures [

	^'discretionary-ligatures'
]

{ #category : #'Font Format' }
CssFontConstants class >> embeddedOpentype [

	^ 'embedded-opentype'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> expanded [
	
	^ 'expanded'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> extraCondensed [

		^ 'extra-condensed'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> extraExpanded [

	^'extra-expanded'
]

{ #category : #'Generic Font Family' }
CssFontConstants class >> fantasy [
	
	^'fantasy'
]

{ #category : #'Font Variant' }
CssFontConstants class >> historicalLigatures [
	
	^ 'historical-ligatures'
]

{ #category : #'Font Size' }
CssFontConstants class >> large [
	
	^'large'
]

{ #category : #'Font Size' }
CssFontConstants class >> larger [
	
	^'larger'
]

{ #category : #'Font Variant' }
CssFontConstants class >> liningNums [
	
	^'lining-nums'
]

{ #category : #'Font Size' }
CssFontConstants class >> medium [
	
	^'medium'
]

{ #category : #'Generic Font Family' }
CssFontConstants class >> monospace [
	
	^ 'monospace'
]

{ #category : #'Font Variant' }
CssFontConstants class >> noCommonLigatures [
	
	^'no-common-ligatures'
]

{ #category : #'Font Variant' }
CssFontConstants class >> noContextual [
	
	^'no-contextual'
]

{ #category : #'Font Variant' }
CssFontConstants class >> noDiscretionaryLigatures [
	
	^ 'no-discretionary-ligatures'
]

{ #category : #'Font Variant' }
CssFontConstants class >> noHistoricalLigatures [
	
	^ 'no-historical-ligatures'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> normal [
	
	^CssConstants normal
]

{ #category : #'Font Variant' }
CssFontConstants class >> oldstyleNums [

	^'oldstyle-nums'
]

{ #category : #'Font Format' }
CssFontConstants class >> opentype [

	^ 'opentype'
]

{ #category : #'Font Variant' }
CssFontConstants class >> ordinal [
	
	^'ordinal'
]

{ #category : #'Font Variant' }
CssFontConstants class >> petiteCaps [
	^ 'petite-caps'
]

{ #category : #'Font Variant' }
CssFontConstants class >> proportionalNums [
	
	^'proportional-nums'
]

{ #category : #'Generic Font Family' }
CssFontConstants class >> sansSerif [
	
	^ 'sans-serif'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> semiCondensed [
	
	^ 'semi-condensed'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> semiExpanded [
	
	^ 'semi-expanded'
]

{ #category : #'Generic Font Family' }
CssFontConstants class >> serif [
	
	^'serif'
]

{ #category : #'Font Variant' }
CssFontConstants class >> slashedZero [
	
	^'slashed-zero'
]

{ #category : #'Font Size' }
CssFontConstants class >> small [
	
	^'small'
]

{ #category : #'Font Variant' }
CssFontConstants class >> smallCaps [
	
	^CssConstants smallCaps 
]

{ #category : #'Font Size' }
CssFontConstants class >> smaller [
	
	^'smaller'
]

{ #category : #'Font Variant' }
CssFontConstants class >> stackedFractions [
	
	^'stacked-fractions'
]

{ #category : #'Font Synthesis' }
CssFontConstants class >> style [
	
	^'style'
]

{ #category : #'Font Variant' }
CssFontConstants class >> sub [
	
	^'sub'
]

{ #category : #'Font Variant' }
CssFontConstants class >> super [
	
	^'super'
]

{ #category : #'Font Format' }
CssFontConstants class >> svg [

	^ 'svg'
]

{ #category : #'Font Variant' }
CssFontConstants class >> tabularNums [
	
	^'tabular-nums'
]

{ #category : #'Font Variant' }
CssFontConstants class >> titlingCaps [
	
	^'titling-caps'
]

{ #category : #'Font Format' }
CssFontConstants class >> truetype [

	^ 'truetype'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> ultraCondensed [
	
	^ 'ultra-condensed'
]

{ #category : #'Font Stretching' }
CssFontConstants class >> ultraExpanded [

		^ 'ultra-expanded'
]

{ #category : #'Font Variant' }
CssFontConstants class >> unicase [

	^'unicase'
]

{ #category : #'Font Synthesis' }
CssFontConstants class >> weight [
	
	^'weight'
]

{ #category : #'Font Format' }
CssFontConstants class >> woff [

	^ 'woff'
]

{ #category : #'Font Size' }
CssFontConstants class >> xLarge [
	
	^'x-large'
]

{ #category : #'Font Size' }
CssFontConstants class >> xSmall [
	
	^'x-small'
]

{ #category : #'Font Size' }
CssFontConstants class >> xxLarge [
	
	^'xx-large'
]

{ #category : #'Font Size' }
CssFontConstants class >> xxSmall [
	
	^'xx-small'
]
