"
A CssMediaTypes is a shared pool providing access to the commonly used media types

"
Class {
	#name : #CssMediaQueryConstants,
	#superclass : #Object,
	#category : 'RenoirSt-MediaQueries'
}

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> braille [

	^ 'braille' 
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> embossed [

	^ 'embossed' 
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> handheld [

	^ 'handheld'  
]

{ #category : #'Accessing - Scan' }
CssMediaQueryConstants class >> interlace [
	
	^'interlace'
]

{ #category : #'Accessing - Orientation' }
CssMediaQueryConstants class >> landscape [

	^ 'landscape' 
]

{ #category : #'Accessing - Orientation' }
CssMediaQueryConstants class >> portrait [

	^ 'portrait' 
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> print [

	^ 'print'
]

{ #category : #'Accessing - Scan' }
CssMediaQueryConstants class >> progressive [

	^ 'progressive'
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> projection [

	^ 'projection' 
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> screen [

	^ 'screen'
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> speech [

	^ 'speech' 
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> tty [

	^ 'tty'
]

{ #category : #'Accessing - Media Types' }
CssMediaQueryConstants class >> tv [

	^ 'tv'
]
