"
A CssSVGColors class is pool dictonary providing easy access to the SVG 1.0 color list
See http://www.w3.org/TR/2011/REC-css3-color-20110607/#svg-color
"
Class {
	#name : #CssSVGColors,
	#superclass : #Object,
	#classVars : [
		'AliceBlue',
		'AntiqueWhite',
		'Aqua',
		'Aquamarine',
		'Azure',
		'Beige',
		'Bisque',
		'Black',
		'BlanchedAlmond',
		'Blue',
		'Blueviolet',
		'Brown',
		'Burlywood',
		'CadetBlue',
		'Chartreuse',
		'Chocolate',
		'Coral',
		'CornflowerBlue',
		'Cornsilk',
		'Crimson',
		'Cyan',
		'DarkBlue',
		'DarkCyan',
		'DarkGoldenrod',
		'DarkGray',
		'DarkGreen',
		'DarkGrey',
		'DarkKhaki',
		'DarkMagenta',
		'DarkOliveGreen',
		'DarkOrange',
		'DarkOrchid',
		'DarkRed',
		'DarkSalmon',
		'DarkSeaGreen',
		'DarkSlateBlue',
		'DarkSlateGray',
		'DarkSlateGrey',
		'DarkTurquoise',
		'DarkViolet',
		'DeepPink',
		'DeepSkyBlue',
		'DimGray',
		'DimGrey',
		'DodgerBlue',
		'Firebrick',
		'FloralWhite',
		'ForestGreen',
		'Fuchsia',
		'Gainsboro',
		'GhostWhite',
		'Gold',
		'Goldenrod',
		'Gray',
		'Green',
		'GreenYellow',
		'Grey',
		'Honeydew',
		'HotPink',
		'IndianRed',
		'Indigo',
		'Ivory',
		'Khaki',
		'Lavender',
		'LavenderBlush',
		'LawnGreen',
		'LemonChiffon',
		'LightBlue',
		'LightCoral',
		'LightCyan',
		'LightGoldenrodYellow',
		'LightGray',
		'LightGreen',
		'LightGrey',
		'LightPink',
		'LightSalmon',
		'LightSeaGreen',
		'LightSkyBlue',
		'LightSlateGray',
		'LightSlateGrey',
		'LightSteelBlue',
		'LightYellow',
		'Lime',
		'LimeGreen',
		'Linen',
		'Magenta',
		'Maroon',
		'MediumAquamarine',
		'MediumBlue',
		'MediumOrchid',
		'MediumPurple',
		'MediumSeaGreen',
		'MediumSlateBlue',
		'MediumSpringGreen',
		'MediumTurquoise',
		'MediumVioletRed',
		'MidnightBlue',
		'MintCream',
		'MistyRose',
		'Moccasin',
		'NavajoWhite',
		'Navy',
		'Oldlace',
		'Olive',
		'Olivedrab',
		'Orange',
		'OrangeRed',
		'Orchid',
		'PaleGoldenrod',
		'PaleGreen',
		'PaleTurquoise',
		'PaleVioletRed',
		'PapayaWhip',
		'Peachpuff',
		'Peru',
		'Pink',
		'Plum',
		'PowderBlue',
		'Purple',
		'Red',
		'RosyBrown',
		'RoyalBlue',
		'SaddleBrown',
		'Salmon',
		'SandyBrown',
		'SeaGreen',
		'SeaShell',
		'Sienna',
		'Silver',
		'SkyBlue',
		'SlateBlue',
		'SlateGray',
		'SlateGrey',
		'Snow',
		'SpringGreen',
		'SteelBlue',
		'Tan',
		'Teal',
		'Thistle',
		'Tomato',
		'Turquoise',
		'Violet',
		'Wheat',
		'White',
		'WhiteSmoke',
		'Yellow',
		'YellowGreen'
	],
	#category : #'RenoirSt-Colors'
}

{ #category : #accessing }
CssSVGColors class >> aliceBlue [
	^ AliceBlue
]

{ #category : #accessing }
CssSVGColors class >> antiqueWhite [
	^ AntiqueWhite
]

{ #category : #accessing }
CssSVGColors class >> aqua [
	^ Aqua
]

{ #category : #accessing }
CssSVGColors class >> aquamarine [
	^ Aquamarine
]

{ #category : #accessing }
CssSVGColors class >> azure [
	^ Azure
]

{ #category : #accessing }
CssSVGColors class >> beige [
	^ Beige
]

{ #category : #accessing }
CssSVGColors class >> bisque [
	^ Bisque
]

{ #category : #accessing }
CssSVGColors class >> black [
	^ Black
]

{ #category : #accessing }
CssSVGColors class >> blanchedAlmond [
	^ BlanchedAlmond
]

{ #category : #accessing }
CssSVGColors class >> blue [
	^ Blue
]

{ #category : #accessing }
CssSVGColors class >> blueviolet [
	^ Blueviolet
]

{ #category : #accessing }
CssSVGColors class >> brown [
	^ Brown
]

{ #category : #accessing }
CssSVGColors class >> burlywood [
	^ Burlywood
]

{ #category : #accessing }
CssSVGColors class >> cadetBlue [
	^ CadetBlue
]

{ #category : #accessing }
CssSVGColors class >> chartreuse [
	^ Chartreuse
]

{ #category : #accessing }
CssSVGColors class >> chocolate [
	^ Chocolate
]

{ #category : #accessing }
CssSVGColors class >> coral [
	^ Coral
]

{ #category : #accessing }
CssSVGColors class >> cornflowerBlue [
	^ CornflowerBlue
]

{ #category : #accessing }
CssSVGColors class >> cornsilk [
	^ Cornsilk
]

{ #category : #accessing }
CssSVGColors class >> crimson [
	^ Crimson
]

{ #category : #accessing }
CssSVGColors class >> cyan [
	^ Cyan
]

{ #category : #accessing }
CssSVGColors class >> darkBlue [
	^ DarkBlue
]

{ #category : #accessing }
CssSVGColors class >> darkCyan [
	^ DarkCyan
]

{ #category : #accessing }
CssSVGColors class >> darkGoldenrod [
	^ DarkGoldenrod
]

{ #category : #accessing }
CssSVGColors class >> darkGray [
	^ DarkGray
]

{ #category : #accessing }
CssSVGColors class >> darkGreen [
	^ DarkGreen
]

{ #category : #accessing }
CssSVGColors class >> darkGrey [
	^ DarkGrey
]

{ #category : #accessing }
CssSVGColors class >> darkKhaki [
	^ DarkKhaki
]

{ #category : #accessing }
CssSVGColors class >> darkMagenta [
	^ DarkMagenta
]

{ #category : #accessing }
CssSVGColors class >> darkOliveGreen [
	^ DarkOliveGreen
]

{ #category : #accessing }
CssSVGColors class >> darkOrange [
	^ DarkOrange
]

{ #category : #accessing }
CssSVGColors class >> darkOrchid [
	^ DarkOrchid
]

{ #category : #accessing }
CssSVGColors class >> darkRed [
	^ DarkRed
]

{ #category : #accessing }
CssSVGColors class >> darkSalmon [
	^ DarkSalmon
]

{ #category : #accessing }
CssSVGColors class >> darkSeaGreen [
	^ DarkSeaGreen
]

{ #category : #accessing }
CssSVGColors class >> darkSlateBlue [
	^ DarkSlateBlue
]

{ #category : #accessing }
CssSVGColors class >> darkSlateGray [
	^ DarkSlateGray
]

{ #category : #accessing }
CssSVGColors class >> darkSlateGrey [
	^ DarkSlateGrey
]

{ #category : #accessing }
CssSVGColors class >> darkTurquoise [
	^ DarkTurquoise
]

{ #category : #accessing }
CssSVGColors class >> darkViolet [
	^ DarkViolet
]

{ #category : #accessing }
CssSVGColors class >> deepPink [
	^ DeepPink
]

{ #category : #accessing }
CssSVGColors class >> deepSkyBlue [
	^ DeepSkyBlue
]

{ #category : #accessing }
CssSVGColors class >> dimGray [
	^ DimGray
]

{ #category : #accessing }
CssSVGColors class >> dimGrey [
	^ DimGrey
]

{ #category : #accessing }
CssSVGColors class >> dodgerBlue [
	^ DodgerBlue
]

{ #category : #accessing }
CssSVGColors class >> firebrick [
	^ Firebrick
]

{ #category : #accessing }
CssSVGColors class >> floralWhite [
	^ FloralWhite
]

{ #category : #accessing }
CssSVGColors class >> forestGreen [
	^ ForestGreen
]

{ #category : #accessing }
CssSVGColors class >> fuchsia [
	^ Fuchsia
]

{ #category : #accessing }
CssSVGColors class >> gainsboro [
	^ Gainsboro
]

{ #category : #accessing }
CssSVGColors class >> ghostWhite [
	^ GhostWhite
]

{ #category : #accessing }
CssSVGColors class >> gold [
	^ Gold
]

{ #category : #accessing }
CssSVGColors class >> goldenrod [
	^ Goldenrod
]

{ #category : #accessing }
CssSVGColors class >> gray [
	^ Gray
]

{ #category : #accessing }
CssSVGColors class >> green [
	^ Green
]

{ #category : #accessing }
CssSVGColors class >> greenYellow [
	^ GreenYellow
]

{ #category : #accessing }
CssSVGColors class >> grey [
	^ Grey
]

{ #category : #accessing }
CssSVGColors class >> honeydew [
	^ Honeydew
]

{ #category : #accessing }
CssSVGColors class >> hotPink [
	^ HotPink
]

{ #category : #accessing }
CssSVGColors class >> indianRed [
	^ IndianRed
]

{ #category : #accessing }
CssSVGColors class >> indigo [
	^ Indigo
]

{ #category : #'initialize-release' }
CssSVGColors class >> initialize [

	<ignoreForCoverage>
	self
		initializeAtoF;
		initializeGtoL;
		initializeMtoZ
]

{ #category : #private }
CssSVGColors class >> initializeAtoF [

	<ignoreForCoverage>
	AliceBlue := (CssRGBColor red: 240 green: 248 blue: 255) identifiedBy: 'aliceblue'.
	AntiqueWhite := (CssRGBColor red: 250 green: 235 blue: 215) identifiedBy: 'antiquewhite'.
	Aqua := (CssRGBColor red: 0 green: 255 blue: 255) identifiedBy: 'aqua'.
	Aquamarine := (CssRGBColor red: 127 green: 255 blue: 212) identifiedBy: 'aquamarine'.
	Azure := (CssRGBColor red: 240 green: 255 blue: 255) identifiedBy: 'azure'.
	Beige := (CssRGBColor red: 245 green: 245 blue: 220) identifiedBy: 'beige'.
	Bisque := (CssRGBColor red: 255 green: 228 blue: 196) identifiedBy: 'bisque'.
	Black := (CssRGBColor red: 0 green: 0 blue: 0) identifiedBy: 'black'.
	BlanchedAlmond := (CssRGBColor red: 255 green: 235 blue: 205) identifiedBy: 'blanchedalmond'.
	Blue := (CssRGBColor red: 0 green: 0 blue: 255) identifiedBy: 'blue'.
	Blueviolet := (CssRGBColor red: 138 green: 43 blue: 226) identifiedBy: 'blueviolet'.
	Brown := (CssRGBColor red: 165 green: 42 blue: 42) identifiedBy: 'brown'.
	Burlywood := (CssRGBColor red: 222 green: 184 blue: 135) identifiedBy: 'burlywood'.
	CadetBlue := (CssRGBColor red: 95 green: 158 blue: 160) identifiedBy: 'cadetblue'.
	Chartreuse := (CssRGBColor red: 127 green: 255 blue: 0) identifiedBy: 'chartreuse'.
	Chocolate := (CssRGBColor red: 210 green: 105 blue: 30) identifiedBy: 'chocolate'.
	Coral := (CssRGBColor red: 255 green: 127 blue: 80) identifiedBy: 'coral'.
	CornflowerBlue := (CssRGBColor red: 100 green: 149 blue: 237) identifiedBy: 'cornflowerblue'.
	Cornsilk := (CssRGBColor red: 255 green: 248 blue: 220) identifiedBy: 'cornsilk'.
	Crimson := (CssRGBColor red: 220 green: 20 blue: 60) identifiedBy: 'crimson'.
	Cyan := (CssRGBColor red: 0 green: 255 blue: 255) identifiedBy: 'cyan'.
	DarkBlue := (CssRGBColor red: 0 green: 0 blue: 139) identifiedBy: 'darkblue'.
	DarkCyan := (CssRGBColor red: 0 green: 139 blue: 139) identifiedBy: 'darkcyan'.
	DarkGoldenrod := (CssRGBColor red: 184 green: 134 blue: 11) identifiedBy: 'darkgoldenrod'.
	DarkGray := (CssRGBColor red: 169 green: 169 blue: 169) identifiedBy: 'darkgray'.
	DarkGreen := (CssRGBColor red: 0 green: 100 blue: 0) identifiedBy: 'darkgreen'.
	DarkGrey := (CssRGBColor red: 169 green: 169 blue: 169) identifiedBy: 'darkgrey'.
	DarkKhaki := (CssRGBColor red: 189 green: 183 blue: 107) identifiedBy: 'darkkhaki'.
	DarkMagenta := (CssRGBColor red: 139 green: 0 blue: 139) identifiedBy: 'darkmagenta'.
	DarkOliveGreen := (CssRGBColor red: 85 green: 107 blue: 47) identifiedBy: 'darkolivegreen'.
	DarkOrange := (CssRGBColor red: 255 green: 140 blue: 0) identifiedBy: 'darkorange'.
	DarkOrchid := (CssRGBColor red: 153 green: 50 blue: 204) identifiedBy: 'darkorchid'.
	DarkRed := (CssRGBColor red: 139 green: 0 blue: 0) identifiedBy: 'darkred'.
	DarkSalmon := (CssRGBColor red: 233 green: 150 blue: 122) identifiedBy: 'darksalmon'.
	DarkSeaGreen := (CssRGBColor red: 143 green: 188 blue: 143) identifiedBy: 'darkseagreen'.
	DarkSlateBlue := (CssRGBColor red: 72 green: 61 blue: 139) identifiedBy: 'darkslateblue'.
	DarkSlateGray := (CssRGBColor red: 47 green: 79 blue: 79) identifiedBy: 'darkslategray'.
	DarkSlateGrey := (CssRGBColor red: 47 green: 79 blue: 79) identifiedBy: 'darkslategrey'.
	DarkTurquoise := (CssRGBColor red: 0 green: 206 blue: 209) identifiedBy: 'darkturquoise'.
	DarkViolet := (CssRGBColor red: 148 green: 0 blue: 211) identifiedBy: 'darkviolet'.
	DeepPink := (CssRGBColor red: 255 green: 20 blue: 147) identifiedBy: 'deeppink'.
	DeepSkyBlue := (CssRGBColor red: 0 green: 191 blue: 255) identifiedBy: 'deepskyblue'.
	DimGray := (CssRGBColor red: 105 green: 105 blue: 105) identifiedBy: 'dimgray'.
	DimGrey := (CssRGBColor red: 105 green: 105 blue: 105) identifiedBy: 'dimgrey'.
	DodgerBlue := (CssRGBColor red: 30 green: 144 blue: 255) identifiedBy: 'dodgerblue'.
	Firebrick := (CssRGBColor red: 178 green: 34 blue: 34) identifiedBy: 'firebrick'.
	FloralWhite := (CssRGBColor red: 255 green: 250 blue: 240) identifiedBy: 'floralwhite'.
	ForestGreen := (CssRGBColor red: 34 green: 139 blue: 34) identifiedBy: 'forestgreen'.
	Fuchsia := (CssRGBColor red: 255 green: 0 blue: 255) identifiedBy: 'fuchsia'
]

{ #category : #private }
CssSVGColors class >> initializeGtoL [

	<ignoreForCoverage>
	Gainsboro := (CssRGBColor red: 220 green: 220 blue: 220) identifiedBy: 'gainsboro'.
	GhostWhite := (CssRGBColor red: 248 green: 248 blue: 255) identifiedBy: 'ghostwhite'.
	Gold := (CssRGBColor red: 255 green: 215 blue: 0) identifiedBy: 'gold'.
	Goldenrod := (CssRGBColor red: 218 green: 165 blue: 32) identifiedBy: 'goldenrod'.
	Gray := (CssRGBColor red: 128 green: 128 blue: 128) identifiedBy: 'gray'.
	Green := (CssRGBColor red: 0 green: 128 blue: 0) identifiedBy: 'green'.
	GreenYellow := (CssRGBColor red: 173 green: 255 blue: 47) identifiedBy: 'greenyellow'.
	Grey := (CssRGBColor red: 128 green: 128 blue: 128) identifiedBy: 'grey'.
	Honeydew := (CssRGBColor red: 240 green: 255 blue: 240) identifiedBy: 'honeydew'.
	HotPink := (CssRGBColor red: 255 green: 105 blue: 180) identifiedBy: 'hotpink'.
	IndianRed := (CssRGBColor red: 205 green: 92 blue: 92) identifiedBy: 'indianred'.
	Indigo := (CssRGBColor red: 75 green: 0 blue: 130) identifiedBy: 'indigo'.
	Ivory := (CssRGBColor red: 255 green: 255 blue: 240) identifiedBy: 'ivory'.
	Khaki := (CssRGBColor red: 240 green: 230 blue: 140) identifiedBy: 'khaki'.
	Lavender := (CssRGBColor red: 230 green: 230 blue: 250) identifiedBy: 'lavender'.
	LavenderBlush := (CssRGBColor red: 255 green: 240 blue: 245) identifiedBy: 'lavenderblush'.
	LawnGreen := (CssRGBColor red: 124 green: 252 blue: 0) identifiedBy: 'lawngreen'.
	LemonChiffon := (CssRGBColor red: 255 green: 250 blue: 205) identifiedBy: 'lemonchiffon'.
	LightBlue := (CssRGBColor red: 173 green: 216 blue: 230) identifiedBy: 'lightblue'.
	LightCoral := (CssRGBColor red: 240 green: 128 blue: 128) identifiedBy: 'lightcoral'.
	LightCyan := (CssRGBColor red: 224 green: 255 blue: 255) identifiedBy: 'lightcyan'.
	LightGoldenrodYellow := (CssRGBColor red: 250 green: 250 blue: 210) identifiedBy: 'lightgoldenrodyellow'.
	LightGray := (CssRGBColor red: 211 green: 211 blue: 211) identifiedBy: 'lightgray'.
	LightGreen := (CssRGBColor red: 144 green: 238 blue: 144) identifiedBy: 'lightgreen'.
	LightGrey := (CssRGBColor red: 211 green: 211 blue: 211) identifiedBy: 'lightgrey'.
	LightPink := (CssRGBColor red: 255 green: 182 blue: 193) identifiedBy: 'lightpink'.
	LightSalmon := (CssRGBColor red: 255 green: 160 blue: 122) identifiedBy: 'lightsalmon'.
	LightSeaGreen := (CssRGBColor red: 32 green: 178 blue: 170) identifiedBy: 'lightseagreen'.
	LightSkyBlue := (CssRGBColor red: 135 green: 206 blue: 250) identifiedBy: 'lightskyblue'.
	LightSlateGray := (CssRGBColor red: 119 green: 136 blue: 153) identifiedBy: 'lightslategray'.
	LightSlateGrey := (CssRGBColor red: 119 green: 136 blue: 153) identifiedBy: 'lightslategrey'.
	LightSteelBlue := (CssRGBColor red: 176 green: 196 blue: 222) identifiedBy: 'lightsteelblue'.
	LightYellow := (CssRGBColor red: 255 green: 255 blue: 224) identifiedBy: 'lightyellow'.
	Lime := (CssRGBColor red: 0 green: 255 blue: 0) identifiedBy: 'lime'.
	LimeGreen := (CssRGBColor red: 50 green: 205 blue: 50) identifiedBy: 'limegreen'.
	Linen := (CssRGBColor red: 250 green: 240 blue: 230) identifiedBy: 'linen'
]

{ #category : #private }
CssSVGColors class >> initializeMtoZ [

	<ignoreForCoverage>
	Magenta := (CssRGBColor red: 255 green: 0 blue: 255) identifiedBy: 'magenta'.
	Maroon := (CssRGBColor red: 128 green: 0 blue: 0) identifiedBy: 'maroon'.
	MediumAquamarine := (CssRGBColor red: 102 green: 205 blue: 170) identifiedBy: 'mediumaquamarine'.
	MediumBlue := (CssRGBColor red: 0 green: 0 blue: 205) identifiedBy: 'mediumblue'.
	MediumOrchid := (CssRGBColor red: 186 green: 85 blue: 211) identifiedBy: 'mediumorchid'.
	MediumPurple := (CssRGBColor red: 147 green: 112 blue: 219) identifiedBy: 'mediumpurple'.
	MediumSeaGreen := (CssRGBColor red: 60 green: 179 blue: 113) identifiedBy: 'mediumseagreen'.
	MediumSlateBlue := (CssRGBColor red: 123 green: 104 blue: 238) identifiedBy: 'mediumslateblue'.
	MediumSpringGreen := (CssRGBColor red: 0 green: 250 blue: 154) identifiedBy: 'mediumspringgreen'.
	MediumTurquoise := (CssRGBColor red: 72 green: 209 blue: 204) identifiedBy: 'mediumturquoise'.
	MediumVioletRed := (CssRGBColor red: 199 green: 21 blue: 133) identifiedBy: 'mediumvioletred'.
	MidnightBlue := (CssRGBColor red: 25 green: 25 blue: 112) identifiedBy: 'midnightblue'.
	MintCream := (CssRGBColor red: 245 green: 255 blue: 250) identifiedBy: 'mintcream'.
	MistyRose := (CssRGBColor red: 255 green: 228 blue: 225) identifiedBy: 'mistyrose'.
	Moccasin := (CssRGBColor red: 255 green: 228 blue: 181) identifiedBy: 'moccasin'.
	NavajoWhite := (CssRGBColor red: 255 green: 222 blue: 173) identifiedBy: 'navajowhite'.
	Navy := (CssRGBColor red: 0 green: 0 blue: 128) identifiedBy: 'navy'.
	Oldlace := (CssRGBColor red: 253 green: 245 blue: 230) identifiedBy: 'oldlace'.
	Olive := (CssRGBColor red: 128 green: 128 blue: 0) identifiedBy: 'olive'.
	Olivedrab := (CssRGBColor red: 107 green: 142 blue: 35) identifiedBy: 'olivedrab'.
	Orange := (CssRGBColor red: 255 green: 165 blue: 0) identifiedBy: 'orange'.
	OrangeRed := (CssRGBColor red: 255 green: 69 blue: 0) identifiedBy: 'orangered'.
	Orchid := (CssRGBColor red: 218 green: 112 blue: 214) identifiedBy: 'orchid'.
	PaleGoldenrod := (CssRGBColor red: 238 green: 232 blue: 170) identifiedBy: 'palegoldenrod'.
	PaleGreen := (CssRGBColor red: 152 green: 251 blue: 152) identifiedBy: 'palegreen'.
	PaleTurquoise := (CssRGBColor red: 175 green: 238 blue: 238) identifiedBy: 'paleturquoise'.
	PaleVioletRed := (CssRGBColor red: 219 green: 112 blue: 147) identifiedBy: 'palevioletred'.
	PapayaWhip := (CssRGBColor red: 255 green: 239 blue: 213) identifiedBy: 'papayawhip'.
	Peachpuff := (CssRGBColor red: 255 green: 218 blue: 185) identifiedBy: 'peachpuff'.
	Peru := (CssRGBColor red: 205 green: 133 blue: 63) identifiedBy: 'peru'.
	Pink := (CssRGBColor red: 255 green: 192 blue: 203) identifiedBy: 'pink'.
	Plum := (CssRGBColor red: 221 green: 160 blue: 221) identifiedBy: 'plum'.
	PowderBlue := (CssRGBColor red: 176 green: 224 blue: 230) identifiedBy: 'powderblue'.
	Purple := (CssRGBColor red: 128 green: 0 blue: 128) identifiedBy: 'purple'.
	Red := (CssRGBColor red: 255 green: 0 blue: 0) identifiedBy: 'red'.
	RosyBrown := (CssRGBColor red: 188 green: 143 blue: 143) identifiedBy: 'rosybrown'.
	RoyalBlue := (CssRGBColor red: 65 green: 105 blue: 225) identifiedBy: 'royalblue'.
	SaddleBrown := (CssRGBColor red: 139 green: 69 blue: 19) identifiedBy: 'saddlebrown'.
	Salmon := (CssRGBColor red: 250 green: 128 blue: 114) identifiedBy: 'salmon'.
	SandyBrown := (CssRGBColor red: 244 green: 164 blue: 96) identifiedBy: 'sandybrown'.
	SeaGreen := (CssRGBColor red: 46 green: 139 blue: 87) identifiedBy: 'seagreen'.
	SeaShell := (CssRGBColor red: 255 green: 245 blue: 238) identifiedBy: 'seashell'.
	Sienna := (CssRGBColor red: 160 green: 82 blue: 45) identifiedBy: 'sienna'.
	Silver := (CssRGBColor red: 192 green: 192 blue: 192) identifiedBy: 'silver'.
	SkyBlue := (CssRGBColor red: 135 green: 206 blue: 235) identifiedBy: 'skyblue'.
	SlateBlue := (CssRGBColor red: 106 green: 90 blue: 205) identifiedBy: 'slateblue'.
	SlateGray := (CssRGBColor red: 112 green: 128 blue: 144) identifiedBy: 'slategray'.
	SlateGrey := (CssRGBColor red: 112 green: 128 blue: 144) identifiedBy: 'slategrey'.
	Snow := (CssRGBColor red: 255 green: 250 blue: 250) identifiedBy: 'snow'.
	SpringGreen := (CssRGBColor red: 0 green: 255 blue: 127) identifiedBy: 'springgreen'.
	SteelBlue := (CssRGBColor red: 70 green: 130 blue: 180) identifiedBy: 'steelblue'.
	Tan := (CssRGBColor red: 210 green: 180 blue: 140) identifiedBy: 'tan'.
	Teal := (CssRGBColor red: 0 green: 128 blue: 128) identifiedBy: 'teal'.
	Thistle := (CssRGBColor red: 216 green: 191 blue: 216) identifiedBy: 'thistle'.
	Tomato := (CssRGBColor red: 255 green: 99 blue: 71) identifiedBy: 'tomato'.
	Turquoise := (CssRGBColor red: 64 green: 224 blue: 208) identifiedBy: 'turquoise'.
	Violet := (CssRGBColor red: 238 green: 130 blue: 238) identifiedBy: 'violet'.
	Wheat := (CssRGBColor red: 245 green: 222 blue: 179) identifiedBy: 'wheat'.
	White := (CssRGBColor red: 255 green: 255 blue: 255) identifiedBy: 'white'.
	WhiteSmoke := (CssRGBColor red: 245 green: 245 blue: 245) identifiedBy: 'whitesmoke'.
	Yellow := (CssRGBColor red: 255 green: 255 blue: 0) identifiedBy: 'yellow'.
	YellowGreen := (CssRGBColor red: 154 green: 205 blue: 50) identifiedBy: 'yellowgreen'
]

{ #category : #accessing }
CssSVGColors class >> ivory [
	^ Ivory
]

{ #category : #accessing }
CssSVGColors class >> khaki [
	^ Khaki
]

{ #category : #accessing }
CssSVGColors class >> lavender [
	^ Lavender
]

{ #category : #accessing }
CssSVGColors class >> lavenderBlush [
	^ LavenderBlush
]

{ #category : #accessing }
CssSVGColors class >> lawnGreen [
	^ LawnGreen
]

{ #category : #accessing }
CssSVGColors class >> lemonChiffon [
	^ LemonChiffon
]

{ #category : #accessing }
CssSVGColors class >> lightBlue [
	^ LightBlue
]

{ #category : #accessing }
CssSVGColors class >> lightCoral [
	^ LightCoral
]

{ #category : #accessing }
CssSVGColors class >> lightCyan [
	^ LightCyan
]

{ #category : #accessing }
CssSVGColors class >> lightGoldenrodYellow [
	^ LightGoldenrodYellow
]

{ #category : #accessing }
CssSVGColors class >> lightGray [
	^ LightGray
]

{ #category : #accessing }
CssSVGColors class >> lightGreen [
	^ LightGreen
]

{ #category : #accessing }
CssSVGColors class >> lightGrey [
	^ LightGrey
]

{ #category : #accessing }
CssSVGColors class >> lightPink [
	^ LightPink
]

{ #category : #accessing }
CssSVGColors class >> lightSalmon [
	^ LightSalmon
]

{ #category : #accessing }
CssSVGColors class >> lightSeaGreen [
	^ LightSeaGreen
]

{ #category : #accessing }
CssSVGColors class >> lightSkyBlue [
	^ LightSkyBlue
]

{ #category : #accessing }
CssSVGColors class >> lightSlateGray [
	^ LightSlateGray
]

{ #category : #accessing }
CssSVGColors class >> lightSlateGrey [
	^ LightSlateGrey
]

{ #category : #accessing }
CssSVGColors class >> lightSteelBlue [
	^ LightSteelBlue
]

{ #category : #accessing }
CssSVGColors class >> lightYellow [
	^ LightYellow
]

{ #category : #accessing }
CssSVGColors class >> lime [
	^ Lime
]

{ #category : #accessing }
CssSVGColors class >> limeGreen [
	^ LimeGreen
]

{ #category : #accessing }
CssSVGColors class >> linen [
	^ Linen
]

{ #category : #accessing }
CssSVGColors class >> magenta [
	^ Magenta
]

{ #category : #accessing }
CssSVGColors class >> maroon [
	^ Maroon
]

{ #category : #accessing }
CssSVGColors class >> mediumAquamarine [
	^ MediumAquamarine
]

{ #category : #accessing }
CssSVGColors class >> mediumBlue [
	^ MediumBlue
]

{ #category : #accessing }
CssSVGColors class >> mediumOrchid [
	^ MediumOrchid
]

{ #category : #accessing }
CssSVGColors class >> mediumPurple [
	^ MediumPurple
]

{ #category : #accessing }
CssSVGColors class >> mediumSeaGreen [
	^ MediumSeaGreen
]

{ #category : #accessing }
CssSVGColors class >> mediumSlateBlue [
	^ MediumSlateBlue
]

{ #category : #accessing }
CssSVGColors class >> mediumSpringGreen [
	^ MediumSpringGreen
]

{ #category : #accessing }
CssSVGColors class >> mediumTurquoise [
	^ MediumTurquoise
]

{ #category : #accessing }
CssSVGColors class >> mediumVioletRed [
	^ MediumVioletRed
]

{ #category : #accessing }
CssSVGColors class >> midnightBlue [
	^ MidnightBlue
]

{ #category : #accessing }
CssSVGColors class >> mintCream [
	^ MintCream
]

{ #category : #accessing }
CssSVGColors class >> mistyRose [
	^ MistyRose
]

{ #category : #accessing }
CssSVGColors class >> moccasin [
	^ Moccasin
]

{ #category : #accessing }
CssSVGColors class >> navajoWhite [
	^ NavajoWhite
]

{ #category : #accessing }
CssSVGColors class >> navy [
	^ Navy
]

{ #category : #accessing }
CssSVGColors class >> oldlace [
	^ Oldlace
]

{ #category : #accessing }
CssSVGColors class >> olive [
	^ Olive
]

{ #category : #accessing }
CssSVGColors class >> olivedrab [
	^ Olivedrab
]

{ #category : #accessing }
CssSVGColors class >> orange [
	^ Orange
]

{ #category : #accessing }
CssSVGColors class >> orangeRed [
	^ OrangeRed
]

{ #category : #accessing }
CssSVGColors class >> orchid [
	^ Orchid
]

{ #category : #accessing }
CssSVGColors class >> paleGoldenrod [
	^ PaleGoldenrod
]

{ #category : #accessing }
CssSVGColors class >> paleGreen [
	^ PaleGreen
]

{ #category : #accessing }
CssSVGColors class >> paleTurquoise [
	^ PaleTurquoise
]

{ #category : #accessing }
CssSVGColors class >> paleVioletRed [
	^ PaleVioletRed
]

{ #category : #accessing }
CssSVGColors class >> papayaWhip [
	^ PapayaWhip
]

{ #category : #accessing }
CssSVGColors class >> peachpuff [
	^ Peachpuff
]

{ #category : #accessing }
CssSVGColors class >> peru [
	^ Peru
]

{ #category : #accessing }
CssSVGColors class >> pink [
	^ Pink
]

{ #category : #accessing }
CssSVGColors class >> plum [
	^ Plum
]

{ #category : #accessing }
CssSVGColors class >> powderBlue [
	^ PowderBlue
]

{ #category : #accessing }
CssSVGColors class >> purple [
	^ Purple
]

{ #category : #accessing }
CssSVGColors class >> red [
	^ Red
]

{ #category : #accessing }
CssSVGColors class >> rosyBrown [
	^ RosyBrown
]

{ #category : #accessing }
CssSVGColors class >> royalBlue [
	^ RoyalBlue
]

{ #category : #accessing }
CssSVGColors class >> saddleBrown [
	^ SaddleBrown
]

{ #category : #accessing }
CssSVGColors class >> salmon [
	^ Salmon
]

{ #category : #accessing }
CssSVGColors class >> sandyBrown [
	^ SandyBrown
]

{ #category : #accessing }
CssSVGColors class >> seaGreen [
	^ SeaGreen
]

{ #category : #accessing }
CssSVGColors class >> seaShell [
	^ SeaShell
]

{ #category : #accessing }
CssSVGColors class >> sienna [
	^ Sienna
]

{ #category : #accessing }
CssSVGColors class >> silver [
	^ Silver
]

{ #category : #accessing }
CssSVGColors class >> skyBlue [
	^ SkyBlue
]

{ #category : #accessing }
CssSVGColors class >> slateBlue [
	^ SlateBlue
]

{ #category : #accessing }
CssSVGColors class >> slateGray [
	^ SlateGray
]

{ #category : #accessing }
CssSVGColors class >> slateGrey [
	^ SlateGrey
]

{ #category : #accessing }
CssSVGColors class >> snow [
	^ Snow
]

{ #category : #accessing }
CssSVGColors class >> springGreen [
	^ SpringGreen
]

{ #category : #accessing }
CssSVGColors class >> steelBlue [
	^ SteelBlue
]

{ #category : #accessing }
CssSVGColors class >> tan [
	^ Tan
]

{ #category : #accessing }
CssSVGColors class >> teal [
	^ Teal
]

{ #category : #accessing }
CssSVGColors class >> thistle [
	^ Thistle
]

{ #category : #accessing }
CssSVGColors class >> tomato [
	^ Tomato
]

{ #category : #accessing }
CssSVGColors class >> transparent [

	^'transparent'
]

{ #category : #accessing }
CssSVGColors class >> turquoise [
	^ Turquoise
]

{ #category : #accessing }
CssSVGColors class >> violet [
	^ Violet
]

{ #category : #accessing }
CssSVGColors class >> wheat [
	^ Wheat
]

{ #category : #accessing }
CssSVGColors class >> white [
	^ White
]

{ #category : #accessing }
CssSVGColors class >> whiteSmoke [
	^ WhiteSmoke
]

{ #category : #accessing }
CssSVGColors class >> yellow [
	^ Yellow
]

{ #category : #accessing }
CssSVGColors class >> yellowGreen [
	^ YellowGreen
]
